### ISSUE TITLE
Gallery image view - bottom bar ... my suggestions... (enhancement?)

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#284] opened 2017-10-30 17:38 UTC
Sorry if there is already an issue for this, I couldn't find one that covered what I wanted to cover. 

In gallery image view the bar along the bottom covers up image content. (This doesn't occur at all screen resolutions, but absolutely occurs at 1080p full screen, which is the most common configuration by far). For many mods this is a problem as they put important image text along the bottom. (For most it's really a non-issue though). 

Even if you click to minimize the bar there's still however many pixels grayed out with the image name in them. Even this small amount can cover up important information if the author formatted their image badly (there really shouldn't be anything important that close to the bottom but sometimes there is). 

In addition, it's not intuitive how to minimize the bar. One could hit esc, or click the grid button. The grid button isn't intuitive, even though I've used it dozens of times now, I still think it's going to take me to a grid view of all the images, not minimize the bar. And once the bar is gone there's no way to bring it back, because the "report a bug" button hides the grid button :P (I know that probably won't be an issue once the "report a bug" button is deprecated but for now it is). 

A few suggestions I've seen:

- Make the bottom bar fade out after a few seconds of not moving the mouse (I do like this one)

- At least make the button to hide the bulk of the bottom bar more intuitive (minimize icon may work better)

**Comment by mrmason** [comment] 2017-10-30 18:05
I think this is a duplicate of #139 - I wasn't aware this was a problem on bigger resolutions - do you have any examples of some problem images that we can take a look at ?

**Comment by Thallassa** [comment] 2017-10-30 19:40
Sure. 

All of the images here have the bottom hair or text along the bottom covered on my screen: https://rd.nexusmods.com/skyrim/mods/10168

If you go about 10-15 images in there are some that also have text obscured by the small bar. 

![image](https://user-images.githubusercontent.com/11600099/32191696-5cb29aea-bd88-11e7-9e0c-3a13b2af0341.png)

![image](https://user-images.githubusercontent.com/11600099/32191729-6b3595ae-bd88-11e7-932f-8d64ce40f490.png)

My apologies for not attaching this to #139 :P

**Comment by m0lz** [comment] 2017-11-09 21:22
Yup, the design currently sucks.

Viewing images is about viewing the whole image, not obscuring parts of it with faded tool bars and titles

Those things may be cool for a website designer but practically we are trying to show full images and all the detail is important.

If you have to keep the faded bars for whatever reason - Resize the image to be presented in full between them. We would lose vertical space but thats better than having the images partially obscured by "cool web design tricks". Current design is bloody annoying.

**Closed** 2018-08-13 08:52 UTC
Labels: layout
