### ISSUE TITLE
error 401 in login process

### ISSUE THREAD

**Issue by viniroxo** [Nexus-Mods/web-issues#1549] opened 2022-06-28 19:59 UTC
## Your username/username(s) affected
Viniceba

## Bug/error being reported:
When trying to log in to the desktop app I get an error 401

## Steps to reproduce:
just try to log in and the 401 error notification appears

## Expected result:
I hope I can login and download the mods

## Actual result:
401 error happens in all the requests I make

**Comment by Pickysaurus** [comment] 2022-06-28 20:16
Duplicate of #1548

**Closed by Pickysaurus** 2022-06-28 20:16 UTC
