### ISSUE TITLE
Fallout 4 mods not showing.

### ISSUE THREAD

**Issue by farukyurdoglu** [Nexus-Mods/web-issues#1458] opened 2022-01-05 19:05 UTC
## Your username/username(s) affected

farukyurdoglu
## Bug/error being reported:

I can see the Fallout 4 mod pages. But I can only see them when I google them and go to their private page. When I sort the Fallout 4 mods, the mods do not appear. The problem is now solved, but I thought it might be someone else and thought I'd report it again.

**Comment by Pickysaurus** [comment] 2022-01-05 19:05
Duplicate of #1454

**Closed by Pickysaurus** 2022-01-05 19:05 UTC
