### ISSUE TITLE
Jumping from first page of images to last results in permanent loading cog.

### ISSUE THREAD

**Issue by JimUKNexus** [Nexus-Mods/web-issues#122] opened 2017-10-03 10:34 UTC
Page https://rd.nexusmods.com/newvegas/users/myaccount?tab=images

My account https://rd.nexusmods.com/users/234717?tab=user+images

**Comment by ousnius** [comment] 2017-10-03 12:06
I can't reproduce this, I can click and jump to the last and any other pages without infinite loading.

**Comment by verenion** [comment] 2017-10-03 16:09
I cannot replicate this either. Can you confirm this is still an issue? Could have been a temporary issue, or could have been fixed by another issue.

**Comment by JimUKNexus** [comment] 2017-10-03 16:19
Tried again and this time it worked, it took about 10 seconds though, earlier it wasn't working at all so something has changed.

**Comment by mrmason** [comment] 2017-10-03 16:20
If it occurs again - can you open the network tab, try again - and see what happens ? Our server should time out after 30-60 seconds and cancel your request if it takes too long - it's possible that is what happened.

**Closed by mrmason** 2017-10-03 16:20 UTC
Labels: cant-replicate

**Comment by JimUKNexus** [comment] 2017-10-03 16:36
I'll do that. It's still taking it's time, my 10 second guess was pretty good. https://puu.sh/xP6IJ/a0024662cb.png
