### ISSUE TITLE
Mod pages redirects to an add

### ISSUE THREAD

**Issue by PhoenixSprite** [Nexus-Mods/web-issues#209] opened 2017-10-25 15:56 UTC
Whenever a mod's page is clicked to download, view images from the mod or other files, no matter where you click on the page, you are redirected to a new tab with an add. Specifically, an add to buy tickets to the league of legends championship.

**Comment by davethegamer** [comment] 2017-10-25 16:29
Yeah they’re aware of it, it’s their ad provider. They said they will fix it soon.

Dark (Official Nexus Discord Moderator): Yeah, that's a very fooking annoying issue our ad provider has introduced, Hopefully they'll sort it when they wake up.

**Comment by verenion** [comment] 2017-10-27 09:07
Duplicate of #203

**Comment by verenion** [comment] 2017-10-27 09:07
This should be resolved now.

**Closed by verenion** 2017-10-27 09:07 UTC
Labels: duplicate
