### ISSUE TITLE
The slow/fast download nag screen is MAJORLY impacting performancce

### ISSUE THREAD

**Issue by Darklocq** [Nexus-Mods/web-issues#1100] opened 2020-02-15 09:06 UTC
## Bug/error being reported:
The semi-new "interrupter" we get, between asking to download a file and actually being able to do so, is rather clumsily coded in 1990s "every change must be a total page reload" style, and it has a really severe impact on ability to get anything done around here.

## Steps to reproduce:
Just go try to download anything from any mod page, as generic user not a high-tier donor. The entire Files page will reload, and you get the nag screen, then you pick "Slow download", and the download starts.  Then to get back to the rest of the files (for most mods of any consequence you need several files), the page completely reloads again.  Aside from making the process take much, much longer than necessary, it's a gross waste of bandwidth.  

## Expected result:
I get why this "pay us!" nag was put there, but it should be working via Ajax or whatever and simply pop something up WITHOUT reloading the entire page, then go away after the download as started.  The old system already used to do this, so it's really weird to me that you broke it just in the course of changing the wording on it and making it bigger to fill most of the viewport.

## Actual result:
Covered above.  This has a really bad impact when you're dealing with a mod that requires a dozens part (patches, etc.).  Like half an hour of screwing around when it should take about 1-2 minutes.  I guess it depends on your connection speed to an extent, but mine's fairly fast, so server speed on your end is also a major factor.  And this has to be causing a lot of resource drain on the servers (which means more cost which means more nagging us to pay – it's a vicious cycle waiting to happen or already happening).

PS: While I get the rationale for doing something LIKE this, it's not just the efficiency problem that's an issue.  The fact that it's using a bogus "Slow download" versus "Fast download" choice is extra-tacky. We all know that "Fast download" doesn't make the download go faster, it goes to a payment form. Higher-paying donors would never see this "interrupt" screen at all.  This thing is modelled directly on download sites that cater to porn and pirated software, which is especially hypocritical given Nexus's anti-piracy position and limits on adult content. 

It would be way more honest to have a choice between "Download with x speed limit" and "Click here to subscribe for faster service" or something.

All that said, I actually DID pay, just at a lower tier (enough to get rid of Nexus-unrelated advertising).  It's a rather off-putting to be treated like a total leech. Try acknowledging that there are different support levels: "We know you're a [whatever kind of member], but to help defray server costs, only [some other kind of member] users can get full download speed.  Click here to download at [x] speed, or click here to upgrade your membership". Something like that. We're not mindless cattle or robots.

I was going to upgrade to a better subscription level a while back already (I'm preparing to do a totally new build-out of Skyrim I expect to use all year, so I need to be on Nexus regularly).  But this inefficient and intelligence-insulting nagware screen is so irritating I can't in good conscience reward you for doing this to us.  So I've been sitting on my money for a few months and will keep doing so until this thing behaves more sensibly.

**Comment by Pickysaurus** [comment] 2020-02-20 11:35
Hi there, 

This is not a bug with the site, it is more your opinion of a site change. Your feedback has been noted but I am going to close this issue report. 

Generally, we ask that users submit constructive feedback on our forums https://forums.nexusmods.com/index.php?/forum/117-feedback-suggestions-and-questions/

We are aware some users do not like these changes and will consider the feedback when we next update the mod pages. 

All the best

**Closed by Pickysaurus** 2020-02-20 11:35 UTC
Labels: invalid

**Comment by Darklocq** [comment] 2020-02-22 11:40
Done.  It's never been very clear to me what Nexus wants reported via this tracker, via forum threads, via messaging admins through report forms, etc.

That said, when this site is entirely set up already with JS that loads pop-up/over elements on the fly without reloading the page, and in fact was already doing this for the version of this screen before (2018 or so), I do actually consider it to be a technical problem to have re-implemented this in a way that clumsily forces the page to entirely reload TWICE just in the course of making a wider "inter-download" message with some nag options.  It's clearly a regression.
