### ISSUE TITLE
Login - Checking your browser before accessing users.nexusmods.com.

### ISSUE THREAD

**Issue by 12port** [Nexus-Mods/web-issues#1504] opened 2022-03-26 14:45 UTC
## Your username/username(s) affected
dtrochman

## Bug/error being reported:

Checking your browser before accessing users.nexusmods.com.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
DDoS protection by [Cloudflare](https://www.cloudflare.com/5xx-error-landing/)

This browser check screen is on an infinite loop when I click to login .

## Expected result:

The login page
## Actual result:

Just a moment (in the tab)
Checking your browser before accessing users.nexusmods.com.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
DDoS protection by [Cloudflare](https://www.cloudflare.com/5xx-error-landing/)

**Comment by Pickysaurus** [comment] 2022-03-26 18:56
Duplicate of #1503

**Closed by Pickysaurus** 2022-03-26 18:56 UTC

**Comment by yorisama** [comment] 2022-03-27 18:39
If you would have left #1503 open - 12Port wouldn't have created a duplicate.  I like his better anyway - really explains well what we are seeing on our end.  Your system automatically has us check for duplicates prior to opening a new ticket.  That system doesn't work if you close tickets - THAT ARE STILL AN ISSUE.
