### ISSUE TITLE
The letter "D" causes the "laugh" emoticon to appear in descriptions

### ISSUE THREAD

**Issue by Spudnik1** [Nexus-Mods/web-issues#272] opened 2017-10-29 19:18 UTC
> **Bug/error being reported:**

 The letter "D" in some mod description pages causes the "laugh" emoticon to appear. It does not appear all the time, but I found it appears mostly when the "D" is uppercase. Examples can be found [here](https://i.imgur.com/XVqraFs.png) and [here](https://i.imgur.com/YXODLwh.png). These two images are from two different nexus game pages, and two different authors. I am on Windows 10 using Google Chrome v61.0.3163.100.

> **Steps to reproduce:**

 Examples of this can be found on The Witcher 3 Nexus [here](https://www.nexusmods.com/witcher3/mods/2662/?) and on the Skyrim SE Nexus [here](https://www.nexusmods.com/skyrimspecialedition/mods/10694/?). I am pretty sure that this is not intentional.

> **Expected result:**

The letter "D" will display normally

> **Actual result:**

The laugh emoticon appears where the "D" is supposed

**Comment by Thallassa** [comment] 2017-10-30 00:08
#239

**Comment by verenion** [comment] 2017-10-30 12:23
Duplicate of #239

**Closed by verenion** 2017-10-30 12:23 UTC
Labels: duplicate
