### ISSUE TITLE
NMM 0.65.2 download no longer functional

### ISSUE THREAD

**Issue by EmperorBirb** [Nexus-Mods/web-issues#749] opened 2018-07-16 03:02 UTC
## Bug/error being reported: NMM 0.65.2 download failure

Upon trying to download Nexus Mod Manager, the download does no pop up. Upon clicking the link in case the download doesn't present, it takes me to this page (image https://gyazo.com/d9b9f3b0f0a878c0abbdd2c7d8739053 )
## Steps to reproduce:

Step 1: Click this: https://gyazo.com/13edc309acb982f36ac0aae9757fe7a1
Step 2: Then this: https://gyazo.com/ae0f1d9a6cdb19550e7aafc6c24b9232
Step 3: Then this: https://gyazo.com/acfea924cda73d9269b0ac7d21e42fb0
Step 4: Then when the download fails to pop, Simply wait for https://gyazo.com/d9b9f3b0f0a878c0abbdd2c7d8739053 to load with the issue
## Expected result:

The download for NMM 0.65.2
## Actual result:

no download and this page being loaded Click this: https://gyazo.com/13edc309acb982f36ac0aae9757fe7a1
Then this: https://gyazo.com/ae0f1d9a6cdb19550e7aafc6c24b9232
Then this: https://gyazo.com/acfea924cda73d9269b0ac7d21e42fb0
Then when the download fails to pop, https://gyazo.com/d9b9f3b0f0a878c0abbdd2c7d8739053 this page loads

**Comment by Drarck** [comment] 2018-07-16 03:33
Same issue with actually all manual downloads on the page.

**Comment by doughsay** [comment] 2018-07-16 05:09
Duplicate of this: https://github.com/Nexus-Mods/web-issues/issues/748
CDN seems to be down.

**Comment by mrmason** [comment] 2018-07-16 07:14
This should be working now, I'll be taking steps today to try and stop this happening again.

**Closed by mrmason** 2018-07-16 07:14 UTC
