### ISSUE TITLE
Files are disabled for this game

### ISSUE THREAD

**Issue by Dalekkar** [Nexus-Mods/web-issues#860] opened 2018-11-01 13:09 UTC
## Bug/error being reported:

Some mods i try to manually download for stardew valley keeps giving this error messaage

## Result:

![image](https://user-images.githubusercontent.com/37339135/47853607-de5fde80-dda4-11e8-86aa-1db7610f9e2c.png)

**Comment by daish0** [comment] 2018-11-01 13:29
Having the same issue on FO4 mods for manual download links since like half an hour, or hour.

**Comment by renegadeX48** [comment] 2018-11-01 13:31
having the same issue for skyrim mods too.

**Comment by dabigone20** [comment] 2018-11-01 13:32
I've had the same issue with every mod I've tried to manually download this morning. I've tested with Fallout 4, Skyrim, Stardew Valley, and Subnautica.

**Comment by spud29** [comment] 2018-11-01 13:32
having the same issue i think it's site-wide...

**Comment by daish0** [comment] 2018-11-01 13:33
It's just getting fixed, should be working again.

**Comment by spud29** [comment] 2018-11-01 13:34
can confirm it's fixed now

**Comment by iamtiz** [comment] 2018-11-01 13:34
Fixed

**Closed** 2018-11-01 13:34 UTC

**Comment by renegadeX48** [comment] 2018-11-01 13:36
i can confirm it's fixed now
