### ISSUE TITLE
Cannot update header image for mod

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#589] opened 2018-03-02 14:16 UTC
## Bug/error being reported:
The new layout made the old banner images look horrible, blurry, and pixilated, so I created a new header image for my mod, 1400x400, under 200 KB, JPG, as recommended.  I tried to upload that image in the media management area, using the 'replace' option.  It looked like it was going to upload for a moment, but the bar didn't make any progress, and it soon vanished, going back to the old image as if I had never tried to change it.  I tried several times, with no better progress then the first try.  I did try saving on the page, and refreshing the mod page, but it acts like I never uploaded the new banner.

## Steps to reproduce:
Try uploading an updated banner image using the Manage/Media area and the replace option.

## Expected result:
That I would see the new banner image.

## Actual result:
I see the same old banner image that the new layout has zoomed way in on, making it out of focus, pixilated, and badly cropped.

**Comment by iamtiz** [comment] 2018-03-02 15:03
Which mod are you trying to update?

**Comment by Eolhin** [comment] 2018-03-02 15:21
https://www.nexusmods.com/oblivion/mods/43304/?

Using Chrome.

**Comment by Eolhin** [comment] 2018-03-02 16:02
Here is the new replacement banner.  Very similar to the old one, but higher resolution, as much as is possible from the original image.  However, if the banner is still going to be zoomed way in on, then I might have to replace it with one with blank space added at the sides, so that the effect, after zooming, is what I had originally intended.  But all that depends on being able to upload a replacement banner of any sort.
![tardis ext 132 bannerb1400x400 j](https://user-images.githubusercontent.com/33217711/36908445-160d4be4-1df0-11e8-9796-18845a381987.jpg)

**Comment by monkeyangie** [comment] 2018-03-03 16:42
if it helps, i have the exact same problem, and only happens with some mods.
it just loads the previous image that it was used as banner instead of the new one

**Comment by Eolhin** [comment] 2018-03-03 17:00
Yeah, I am afraid to try entirely deleting the current banner (and then uploading the new one), because there is a good chance the old banner would be gone, AND I still couldn't upload the new one.

**Comment by Eolhin** [comment] 2018-03-03 17:05
If you have a few specific mods that this is happening for you on, could you add their URLs here?  Perhaps with several examples of it, they could better figure out what is happening.  Old banners being zoomed in on, and messed up is bad enough, but if we can't even replace them...  ((sighs))

**Comment by monkeyangie** [comment] 2018-03-03 17:13
sure, this are the mods:

https://www.nexusmods.com/oblivion/mods/47223
https://www.nexusmods.com/oblivion/mods/46995
https://www.nexusmods.com/oblivion/mods/46179
https://www.nexusmods.com/oblivion/mods/46131
https://www.nexusmods.com/oblivion/mods/45685

**Comment by iamtiz** [comment] 2018-03-05 09:14
Assigned #155696855

**Comment by giftfish** [comment] 2018-03-12 17:20
Yep, I'm having the same problem.

https://www.nexusmods.com/masseffect3/mods/438?

I've made multiple attempts and gone to the extent of the following:

1. Removing the existing header image and saving the removal. Then, I reload the mod page to confirm it's gone. It is.
2. Upload a new image. The image I upload is 1400px wide and 185KB. This appears on the site properly.
3. "Crop and Save" new image.
4. This is where things go haywire. The newly cropped image doesn't appear after clicking the "Crop and Save" feature. Instead, the *old header image that I deleted* is back. In addition, if I reload the mod page, it is back there, too.

**Comment by giftfish** [comment] 2018-03-12 17:33
And, upon further investigation, I can verify something has gone wrong with the cropping functionality itself.

I attempted to do the same thing for another mod: https://www.nexusmods.com/masseffect3/mods/412

In it's case, the crop/save worked and the updated image appeared. However, when refreshing the mod page, the header image *is* different, but it doesn't match the newly cropped image.

Newly cropped header image:
![bo_header_mediapage](https://user-images.githubusercontent.com/13645804/37299428-8939bd12-25e0-11e8-84f9-d4aaf88d52fc.PNG)

Header image as it appears on the mod's page:
![bo_header_modpage](https://user-images.githubusercontent.com/13645804/37299437-8d61afda-25e0-11e8-9896-05e604e577ac.PNG)

---

 So, my guess from a non-coding aspect is cropping is broken. That doesn't explain, however, why the site is *restoring* a deleted header image in the case of my previous post.

**Comment by mrmason** [comment] 2018-03-12 17:43
Thanks for all of the information guys - this is a CDN issue where the images aren't being refreshed/updated correctly and so the old image keeps getting served. We're looking at options at fixing this at the moment.

**Comment by giftfish** [comment] 2018-03-15 16:50
In the event that this issue requires some type of manual fix, I want to leave a list of my mods here that this is affecting. All are for Mass Effect 3:

https://www.nexusmods.com/masseffect3/mods/206
https://www.nexusmods.com/masseffect3/mods/412
https://www.nexusmods.com/masseffect3/mods/438

I also want to clarify that it's possible there are *two* issues at play here:

1. The site is not displaying the proportions of _existing_ header images properly. The crop proportion on the Manage > Media page is correct. The crop on the mod's main page is not (and looks significantly worse).

2. The site will not allow a *new* image to be uploaded for the header.

If you use my mod 438 above, you'll also see an interesting result if you go to Manage > Media and click "Crop" in the mod header area _without uploading anything new_.

The image that appears doesn't match the existing header image. This could be related to the CDN issue you're talking about, but it's definitely strange and not-intended behavior.

**Comment by Zur13** [comment] 2018-03-19 08:32
There is a problem with banner on my mod https://www.nexusmods.com/witcher3/mods/496 
Sometimes on page reload appears mod banner that was replaced a few month ago! There no more image on mod page from which that banner was cropped. I didn't change banner for a few month but the problem appeared recently.

The incorrect banner
![nexuserror19](https://user-images.githubusercontent.com/33193255/37585094-98b2e0ae-2b60-11e8-8b85-1725c3fa2b64.png)

The correct banner
![nexuserror19_1](https://user-images.githubusercontent.com/33193255/37585114-a20d1a52-2b60-11e8-9ca8-51ae44a75d0a.png)

**Comment by giftfish** [comment] 2018-03-21 19:12
I have some important, new information on this/these bug(s) that should help. This is a complicated situation, so please bear with what is also a complicated account of facts. 

_NOTE: All images below are of the site viewed at full content width._

**1. There is a problem with the cropping tool itself and seems to stem from some code associated with the old site.** 

Here's one of my mod pages with a correctly functioning header, compared to it's crop:

![me3re_compare](https://user-images.githubusercontent.com/13645804/37729833-4b7f6b08-2cfb-11e8-9b9f-57e482bbee2c.PNG)

And, here's one that isn't working properly, and results in the zoomed in, pixelated image:

![urz_compare](https://user-images.githubusercontent.com/13645804/37729860-63721756-2cfb-11e8-9422-b3004695d0e3.PNG)

Notice that BOTH crops were both done by Nexus and **do not share the same proportions**:

![me3re_crop](https://user-images.githubusercontent.com/13645804/37729967-a523fe1c-2cfb-11e8-97ff-ab39e7828d01.PNG)
![urz_crop](https://user-images.githubusercontent.com/13645804/37729970-a9ed142e-2cfb-11e8-88e7-fa30afeacba6.PNG)

The functioning crop is 1190x340; this is 3.5 aspect ratio. The broken crop is 960x175; this is a 5.49 aspect ratio. 

**960px width is the full content width of the old site design. And, headers were 175px high. That means mods with this problem are using the OLD cropping dimensions.**

![oldsite_header](https://user-images.githubusercontent.com/13645804/37730605-5b3eec7e-2cfd-11e8-94d2-17bd601a2950.PNG)

After discovering this, I attempted to upload a 1300x360px image that matches the div header exactly. This image WILL actually upload to Nexus and it remains visible on the Media page. However,

- It will not appear on the mod main page itself; the header image area remains empty. **This seems to be the CDN problem referenced 9 days ago.**
- The site insists the image needs to be cropped, despite it being the _exact size_ the div requires. Once I attempt to crop and save, then the new image is lost and is replaced by the old image, which appears in the second screenshot in this post. (this is as reported previously)

That is problem 1.

---

**2. The cropping tool is inaccurate, even when it works.**
As seen above, a cropped header image viewed at full width immediately after the crop is 1190x340, which is a 3.5 aspect ratio. In addition, Nexus tells the mod author this, when they upload their image:

> We recommend you use an image size of 1400x400. This will fit best within this area and will retain a consistent look across any sort of device our users browse with. Max file size 200KB. We only accept JPG, PNG or GIF (not animated) images. 

1400x400 is *also* a 3.5 aspect ratio. However, this is *not* the size/aspect ratio used by the site when viewed at full content width. _That_ size is 1300x360, which has a 3.61 aspect ratio:

![divheader_size](https://user-images.githubusercontent.com/13645804/37730980-3c289dc0-2cfe-11e8-8c91-2af3329db38e.PNG)

When placed on the site, the bottom of the cropped image is cut off. That's not a big deal, but a cropping tool should show a 100% accurate representation of the crop -- at least at full width. 

This would mean the cropping tool should crop to a 3.61 ratio, not 3.5.

---

Is there any ETA on when we'll be getting a fix for problem 1?

This problem is affecting a third of my mods, so I'd be very, very surprised if it wasn't affecting a significant amount of other mods, as well. MEHEM for ME3 looks like it's affected. [A Quality World Map with Roads](https://www.nexusmods.com/skyrim/mods/4929) almost certainly has the same problem, as far as Skyrim mods go. It's hard to tell, without being able to see the cropping tool, though.

**Comment by MrTroubleMaker** [comment] 2018-03-22 01:32
I'm having the same issue on some of my mod pages.

**Comment by iamtiz** [comment] 2018-04-02 08:36
We are aware of the issue, but still working to find a definitive solution for it. We'll keep you posted here!

**Comment by iamtiz** [comment] 2018-05-01 09:52
This issue should be now fixed. Could you give it a try please?

**Comment by MrTroubleMaker** [comment] 2018-05-02 05:58
I went though all of my mods and was able to update the header image. Thanks!

Hopefully someone else can confirm theirs is working as well.

**Comment by giftfish** [comment] 2018-05-02 16:06
Yes, the ability to update header images is finally fixed. You can now upload a new image, crop it, and after cropping, the new image is present. 
![header_cropping](https://user-images.githubusercontent.com/13645804/39534898-7c740144-4de7-11e8-8693-155e4dd85284.JPG)
![headerimage_fixed](https://user-images.githubusercontent.com/13645804/39534905-7f4c7a90-4de7-11e8-951a-06b392e4ab27.JPG)

Yay :)

What isn't fixed is the difference in aspect ratio between the cropping dialog and the header image as it exists on the mod page. They are still different. From what I can tell it doesn't result in stretching, but in the bottom of the header image being cut off, when compared to the crop.

This, however, is a separate issue. If Nexus wants to look into fixing it, I can put up a new issue for it.

**Comment by iamtiz** [comment] 2018-05-03 12:42
@giftfish the header ratio should also be fixed now (to 1:3.5)

**Closed** 2018-05-04 09:48 UTC
Labels: bug
