### ISSUE TITLE
nexus website favorites

### ISSUE THREAD

**Issue by itskitt** [Nexus-Mods/web-issues#1462] opened 2022-01-17 22:53 UTC
## Your username/username(s) affected
 itskitt

## Bug/error being reported:

the website is not unfavoriting games so i can favorite others. just keeps saying an error has happened and it was already removed please refresh. but after refreshing nothing happens. someone else reported this problem back in november and you said issue was fixed but its not. please fix it
## Steps to reproduce:

click x in favorite 
said remove from favorites on all 12 games
There was a problem with your request
728 has already been removed. Please refresh and check again.
1151 has already been removed. Please refresh and check again. and so forth for all 12 games
## Expected result:

to have a clean favorites to start favoriting new games
## Actual result:

nothing happened

**Comment by Pickysaurus** [comment] 2022-01-24 15:55
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1443

**Closed by Pickysaurus** 2022-01-24 15:55 UTC
