### ISSUE TITLE
Search filters not working correctly

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#43] opened 2017-09-10 16:50 UTC
Currently search filters are not working as intended. 

I clicked on a category, then unchecked attributes "not lore friendly" "skimpy/sexy" "anime". 

When the page reloaded it said there were only 42 mods remaining, but it didn't show any of the results. 

In addition the attributes I had unchecked now had a check box next to them. 

I attempted to uncheck the attributes again and reload the page. Now it showed zero results. 

https://cdn.discordapp.com/attachments/232170227734020097/356479722680483841/unknown.png

(I didn't get a picture of when it showed "42 results, x number filtered" but didn't have any mod tiles shown).

**Comment by Rrrafau** [comment] 2017-09-11 10:23
Having trouble replicating this. Can you confirm that it's still happening and if so, provide more details, thanks!

**Comment by Thallassa** [comment] 2017-09-11 16:22
Yes, still happening: http://imgur.com/a/eVkHT

Browser details: Firefox 55.0.3 64bit, running ublock origin and noscript (which is disabled for nexus mods). This happened both on my desktop (where I first reported it) and on my laptop at home, same OS (Windows 10 without spring creator's update) and browser setup, but totally different hardware. Disabling ublock has no effect. 

Steps to reproduce: From main skyrim page, clicked on mods > mod categories, then on "alchemy", then went to filter by attributes, unchecked "Include adult files, Only show adult files, Anime, Bodyslide Preset, Not Lore-Friendly, Nudity, Saved games, Sexy/Skimpy, Translation", clicked "apply filters" at the bottom. Then the page did the expected spinny wheel thing and when it loaded produced the result above ^. If at that point I then uncheck the attributes a second time and click "apply filters" again, it produces the result in my original post. 

I attempted to this without any category sorting active and the page is still spinning its wheel after a few minutes (probably optimization issue with so many mods to filter). I attempted to this on other categories and got almost exactly the same results (the number of files it says it's meant to display is different for different categories, but also still inaccurate to what I would expect for those attributes unchecked in that category). 

I also was able to replicate this by going to the https://rd.nexusmods.com/skyrim/mods/ page, selecting a category, applying filter, then unchecking any list of attributes and applying filter again. So it's not something up with being at  https://rd.nexusmods.com/skyrim/mods/categories/68/ specifically. 

Trying to refresh the page or edit category from this point doesn't help, it just shows the same page.

**Comment by ousnius** [comment] 2017-09-11 19:01
I can reproduce Thallassa's problem, don't really have anything to add to her steps.

**Comment by verenion** [comment] 2017-09-12 11:26
Assigned PT#151003990

**Comment by mrmason** [comment] 2017-09-27 09:35
We've pushed some fixes for this - please let us know if you're still experiencing any problems with the search filters.

**Comment by ousnius** [comment] 2017-09-27 10:29
Seems to be working for me so far.

**Comment by Thallassa** [comment] 2017-09-27 12:24
Seems to be fixed. 

I'm still seeing attributes rechecking themselves, but it's purely visual. As a filter it's working. 

https://i.imgur.com/gblUyTf.png

**Comment by ousnius** [comment] 2017-09-27 13:05
The automatic re-checking of the checkboxes didn't happen for me.

**Comment by mrmason** [comment] 2017-09-27 13:14
@Thallassa - Can you try in a fresh browser ( incognito or private mode ) or a different brower - just to make sure there is nothing strange going on with old javascript ?

If it's still happening can you give us the exact steps to reproduce ( including which OS/Browser versions and which game you're on ) - thanks!

**Comment by Thallassa** [comment] 2017-09-27 14:43
Hm. On a fresh browser it doesn't even show all the attributes, just https://i.imgur.com/ovVjc0c.png?1

**Comment by mrmason** [comment] 2017-09-28 08:35
Assigned `PT#151512018` - We're looking further into this for you.

**Comment by mrmason** [comment] 2017-09-28 08:53
We've fixed the filters not showing up correctly when you're not logged in - @Thallassa - can you please let us know if your original problem persists as I'm unable to replicate it on my end.

**Comment by Thallassa** [comment] 2017-09-28 14:11
The only problem that is still persisting is that the attributes re-check themselves after I uncheck them (but the filter does apply). 

Steps to reproduce:

1. Tried two browsers, Firefox 55 and Chrome (latest version). Windows 10, two different computers. 
2. Go to https://rd.nexusmods.com/skyrim/mods/?BH=0 or any category thereof
3. Go to attributes, uncheck any combination (I've been doing all just to be consistent), and click apply
4. Page loads, filter has applied, but the boxes appear checked once again. 

On an unrelated note, since filtering is done in javascript(?) now, it means that I can't share a link for a search that's been filtered to show the results someone might want?

**Comment by mrmason** [comment] 2017-10-11 14:22
Currently you won't be able to share a specific search, no - but we should be able to add it in once all of the bugs are fixed. 

I've assigned `PT#151882580` to the select box issue.

**Comment by mrmason** [comment] 2017-10-11 14:23
Actually I'm going to close this bug and create a new one as it's getting a bit confusing.

**Closed by mrmason** 2017-10-11 14:23 UTC
Labels: bug

**Comment by mrmason** [comment] 2017-10-11 14:25
Opened 145
