### ISSUE TITLE
text gets stripped by javascript

### ISSUE THREAD

**Issue by FruitsBerriesMelons123** [Nexus-Mods/web-issues#1627] opened 2022-12-12 07:14 UTC
## Your username/username(s) affected
FruitsBerriesMelons123

## Bug/error being reported:
Text is being replaced both in my comment section and in the description for my files so I had to make an image and link to it instead: https://i.snipboard.io/uDW0t1.jpg
I can't write: AdditionalIngredientsToProtect=Bear Claws,Wheat
It gets replaced with: Additijavascript-event-strippedBear Claws,Wheat

## Steps to reproduce:
1. Try to make a comment or a file description with:  AdditionalIngredientsToProtect=Bear Claws,Wheat

## Expected result:
It shouldn't be replaced with: Additijavascript-event-strippedBear Claws,Wheat

## Actual result:
It was replaced with: Additijavascript-event-strippedBear Claws,Wheat

**Comment by Pickysaurus** [comment] 2022-12-12 10:31
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1591

**Closed by Pickysaurus** 2022-12-12 10:31 UTC
