### ISSUE TITLE
Can't upload images for mod

### ISSUE THREAD

**Issue by greyday01** [Nexus-Mods/web-issues#1200] opened 2020-09-14 08:30 UTC
When I try to add images to my mod
https://www.nexusmods.com/skyrim/mods/edit/?step=media&id=91408

I drag a jpg image onto the "Drop an image here to upload" box.
There is a green progress bar and a message below saying "uploading" with file name
When that finishes a popup at top of screen says "www.nexusmods.com says "" with an [OK] prompt at bottom.
But no image
size of images are ~900K or less
My mod file uploaded ok, just can't upload images.

**Comment by Pickysaurus** [comment] 2020-09-14 08:40
Duplicate of #1198 please can you respond to that issue with the information from the page footer requested?

**Closed by Pickysaurus** 2020-09-14 08:40 UTC
