### ISSUE TITLE
Cannot add entries to a mod's bug tracker

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#121] opened 2017-10-03 07:16 UTC
Attempting to report a bug on one of my mods does nothing: when I submit the bug report, it never actually gets added to the mod page. It just gets eaten by the void.

Affected mod:
https://www.nexusmods.com/skyrim/mods/78990/

Firefox 55.0.3 32-bit.

**Comment by verenion** [comment] 2017-10-03 09:05
Is this on RD, or on the legacy website?

**Comment by DavidJCobb** [comment] 2017-10-03 21:46
It was on RD.

**Comment by Thallassa** [comment] 2017-10-06 16:40
Can confirm, I tried to submit a bug to CACO's page and it got eaten by the void too.

**Comment by redbaron148** [comment] 2017-10-06 20:36
Probably related to this, I cannot reply to a submitted bug report using the new redesigned website.

Affected mod:
https://www.nexusmods.com/fallout4/mods/23988

When I switched back to using the old website I could reply to the bug.

Viewing rd website on Chrome - 61.0.3163.100 64 bit
Viewing old website on Edge - 38.14393.1066.0 64 bit

**Comment by Pickysaurus** [comment] 2017-10-07 19:16
My report #92 is related to this too. Safe to say bug tracker in RD is broken

**Comment by verenion** [comment] 2017-10-10 16:14
Assigned PT#151476364. Duplicate of #92

**Comment by verenion** [comment] 2017-10-11 15:55
Can you still replicate this issue on RD? We have pushed a couple of fixes for this.

**Comment by Pickysaurus** [comment] 2017-10-11 16:16
I've not had problems adding reports, but replying to reports seems to fail almost every time. I thought it was related to the status changing drop down (which doesn't match the wording of the new site btw) - but it just seems to be random.

**Comment by DavidJCobb** [comment] 2017-10-11 23:28
I successfully filed a new bug on the bug tracker for one of my other mods. I can't attest to replying to bugs.

**Comment by redbaron148** [comment] 2017-10-12 00:55
I was able to successfully add a comment on a bug being tracked for one of my mods using the rd website.

**Comment by verenion** [comment] 2017-10-12 09:41
Adding reports seems to be fine then, I've been trying to replicate the error when adding replies, but still cannot. @Pickysaurus what mod are you trying to add a reply to?

**Comment by Pickysaurus** [comment] 2017-10-12 12:46
https://rd.nexusmods.com/skyrimspecialedition/mods/11802/?
Generally this one or this one
https://rd.nexusmods.com/skyrim/mods/52248/?
It's difficult to say exactly how to replicate it but it happens a LOT. Usually I can reply to one bug, then any follow up posts error out - but sometimes even the first one fails. And it seems adjusting the status of the report makes the problem worse.

**Comment by verenion** [comment] 2017-10-13 11:31
Adjusting the status of a mod actually has nothing to do with posting - when you change the status, that's done separately via ajax. I still cannot replicate this, but I have fixed a couple of small issues that were being caused by special characters - maybe this was causing some of the comments to fail. 

If you could keep your eye out and check if you are still getting this issue, that would be great.

**Comment by Pickysaurus** [comment] 2017-10-13 11:32
Will do, I do use dashes a lot of my replies... Maybe that was it. Seems to be a lot more stable the last couple of days. Thanks for your hard work :D

**Comment by verenion** [comment] 2017-10-13 11:36
No worries, I found it was unicode characters and "&" symbols causing it to fail. All those should be working fine now, so if it was special characters it should be resolved.

**Closed** 2017-10-13 14:01 UTC
Labels: bug, duplicate
