### ISSUE TITLE
Games in favorite list cannot be removed or replaced

### ISSUE THREAD

**Issue by CDAlyx** [Nexus-Mods/web-issues#1626] opened 2022-12-11 18:16 UTC
## Your username/username(s) affected

TheNeoLoneWolf

## Bug/error being reported:

Games in favorite list cannot be removed or replaced

## Steps to reproduce:

The title should be removed from favorite game list.

## Actual result:

Games that are removed return moments later with error messages saying they were already removed. Error gives a different number presumably based on order game was added to nexus, and says to refresh page, but games are still in list, and new games still cannot be added.

**Comment by Pickysaurus** [comment] 2022-12-12 10:31
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1547

This automatically fixes itself after a few hours.

**Closed by Pickysaurus** 2022-12-12 10:31 UTC
