### ISSUE TITLE
Web-site mods dissapear

### ISSUE THREAD

**Issue by salo2016** [Nexus-Mods/web-issues#1455] opened 2022-01-05 17:18 UTC
## Steps to reproduce:
Open the riftbreaker mod list
![5](https://user-images.githubusercontent.com/62756314/148260516-f2223353-b57d-49f1-aeb9-2ffe8a6eae5c.png)

![Screenshot_1](https://user-images.githubusercontent.com/62756314/148260534-2dc419f5-00ae-468b-9dc9-c34ab0bf3192.png)

-->

## Expected result:
List of mods 

## Actual result:
No mod list appear like nothing is added.

**Comment by Pickysaurus** [comment] 2022-01-05 17:19
Duplicate of #1454

**Closed by Pickysaurus** 2022-01-05 17:19 UTC
