### ISSUE TITLE
Bug reports with embedded images often show the image as base64 text.

### ISSUE THREAD

**Issue by billw2012** [Nexus-Mods/web-issues#1326] opened 2021-03-27 12:29 UTC
## Bug/error being reported:
Bug reports with embedded images often show the image as base64 text.

## Steps to reproduce:
Create a bug with an image embedded. Not sure how often it fails.

### Example:
![image](https://user-images.githubusercontent.com/1453936/112720717-f1385800-8ef7-11eb-9345-02e5dca69d60.png)

## Expected result:
Show the image as an image.

## Actual result:
Base64 text is displayed instead.

**Comment by Pickysaurus** [comment] 2021-03-27 12:40
This is a known issue. Users should not be directly pasting images into the editor, however, this is harder to prevent than it sounds... If you can link to the bug report containing this image I can delete it.

**Comment by Pickysaurus** [comment] 2021-03-29 07:54
This is actually a duplicate of #1260 so we'll continue tracking it there.

**Closed by Pickysaurus** 2021-03-29 07:54 UTC
Labels: bug

**Comment by thany** [comment] 2022-03-15 10:38
> This is a known issue. Users should not be directly pasting images into the editor, however, this is harder to prevent than it sounds... If you can link to the bug report containing this image I can delete it.

"Users should not" is the wrong sentiment.  
"Users do" is more correct, and it's the job of us web developers to deal with it 😉

**Comment by Pickysaurus** [comment] 2022-03-15 11:25
This should have been fixed a while ago.
