### ISSUE TITLE
Even Slightly out of date managers cannot access the update server

### ISSUE THREAD

**Issue by Arkevorkhat** [Nexus-Mods/web-issues#674] opened 2018-05-08 18:01 UTC
## Bug/error being reported:
this isn't a bug per-se, just really shitty practices

## Steps to reproduce:
1: have a copy of NMM 63.14
2: try to update through the interface
### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
that the program could connect to NMM servers without being blackballed

##Actual result
Could not connect to any NMM servers, tried installing vortex, which permanantly fucked my entire installation, couldn't fix without re-installing windows. Fuck you guys.

**Comment by Fixitman333** [comment] 2018-05-08 22:42
It's not a bug. The latest version of NMM is 0.65.0. The change was announced on the site news about 2 weeks ago: https://www.nexusmods.com/skyrimspecialedition/news/13481

**Comment by Arkevorkhat** [comment] 2018-05-08 23:50
@Fixitman333 maybe you should have actually read my original post?
I never stated it was a bug, simply a violation of what people expect when they click "Update." They expect that the program will either:  
A: update the program to the most recent version  
or  
B: give them a link to the most recent download  

This program does neither, it just hangs and gives a cryptic error message about "cannot connect to update server"

**Comment by iamtiz** [comment] 2018-05-09 08:58
Hi there,

I am sorry you had issues with NMM.

Unfortunately, we no longer officially support/work on NMM and provide it "as-is". You can read a little more about this here: https://forums.nexusmods.com/index.php?/topic/5159340-nmm-is-currently-end-of-line-read-why-and-what-this-means/

This GitHub issue tracker is for issues on the site, rather than with NMM or Vortex, so I'm going to close this ticket now to keep things clean.

**Closed by iamtiz** 2018-05-09 08:58 UTC
