### ISSUE TITLE
Bottom Option of Drop Down Lists Impossible to Click

### ISSUE THREAD

**Issue by Dylath** [Nexus-Mods/web-issues#468] opened 2017-12-30 10:01 UTC
Anytime I hover over the plus sign, whether in order to favorite a game or track a mod, the bottom option is unclickable, as the entire box disappears as soon as I get that low.

It may just be my computer, but it should happen with any drop down list from hovering over plus signs

**Comment by Zyphlex** [comment] 2017-12-30 11:11
This is a duplicate of issue 466
https://github.com/Nexus-Mods/web-issues/issues/466

**Closed** 2018-01-03 10:07 UTC
