### ISSUE TITLE
Reattempting to upload a file that was canceled makes you refresh the page and lose all your information

### ISSUE THREAD

**Issue by Mgamerz** [Nexus-Mods/web-issues#1318] opened 2021-03-14 22:01 UTC
## Bug/error being reported:
The 'cancel' button for uploading mod files is pretty much pointless, since it forces you to refresh the page for the page to do anything.

## Steps to reproduce:)
1. Upload a file to a mod page
2. During the upload, click cancel upload
3. While still on the page try uploading a file again

## Expected result:
The uploader would respect the file you uploaded

## Actual result:
It just says you can't upload more than one file at a time. You have to refresh the page, which loses everything you've typed in. 

I write a mod manager that has 3 different games it works on, so I upload the same file to three different game subsites. About 35% of the time the upload just gets to 100% on the bar and then does absolutely nothing. The cancel button doesn't help because I have to refresh the page, which makes me type all of the stuff in again, and it gets very monotonous, very quickly.

Note that this is NOT the cause - I can click cancel while it's still normally uploading at say, 30%, and it still gives me that result.
![image](https://user-images.githubusercontent.com/2738836/111085786-81c96e00-84de-11eb-971c-80ff0f4e180c.png)

**Comment by billw2012** [comment] 2021-03-23 11:11
This happens also when you upload a disallowed file type, it still thinks you are uploading something after it rejects the file.

**Comment by Pickysaurus** [comment] 2021-03-29 16:13
I've raised this internally, however it appears by clicking the "Or browse for files" is a temporary workaround as the bugs you describe are only from drag and drop uploads.

**Comment by Pickysaurus** [comment] 2022-06-01 08:23
This isn't something that can be fixed without completely re-writing the uploader code as it's a limitation of one of the libraries in use.

**Comment by Pickysaurus** [comment] 2022-11-15 14:13
The workaround allows this issue to be avoided. The root cause will not be fixed until we migrate the mod upload form to Nexus Mods Next. The new uploader will be designed not to have these issues.

**Closed by Pickysaurus** 2022-11-15 14:13 UTC
Labels: enhancement
