### ISSUE TITLE
Logging in recursion

### ISSUE THREAD

**Issue by ZdrytchX** [Nexus-Mods/web-issues#1170] opened 2020-07-28 06:10 UTC
## Bug/error being reported:
Loging page recursion can sometimes fail to fetch captcha verification properly. Since it fails to fetch a lot of the time, probably wait a bit longer and then fetch.

## Steps to reproduce:
Logging in may require captcha. When the captcha completes, I have to wait about 4 seconds before pressing in the log-in button otherwise it will just redirect back to the login page recursively.

## Expected result:
Complete captcha, log in, bam, done.

## Actual result:
Reloads log-in page. Should I also mention how inaccurate the hCaptcha AI is sometimes?

**Comment by Pickysaurus** [comment] 2020-07-28 10:55
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1171

**Closed by Pickysaurus** 2020-07-28 10:55 UTC
