### ISSUE TITLE
Saving Description on RD site break linebreaks for Old site

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#101] opened 2017-09-29 09:19 UTC
While this won't be an issue when the old site is turned off, saving my mod page description in RD will cause the old version to lose all it's line breaks and bunch everything up together. I assume the editors handle line breaks differently. 
I wish I'd got a screenshot but one of my fellow modders just spent ages redoing the formatting so I don't want to mess it up again. Happens on all mod page description I have access to;
https://rd.nexusmods.com/skyrimspecialedition/mods/11802/?

**Comment by verenion** [comment] 2017-10-02 08:16
Assigned PT#151514775

**Comment by verenion** [comment] 2017-10-02 09:08
Duplicate of #90

**Closed by verenion** 2017-10-02 09:08 UTC
Labels: bug
