### ISSUE TITLE
Keep getting bombarded with "There was an error fetching your comment's siblings. Comment not found" error

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1195] opened 2020-09-10 20:23 UTC
Whenever I post comments on a Nexus mod page, I keep getting this annoying error message: "There was an error fetching your comment's siblings. Comment not found."  Doesn't happen all the time but has become more frequent & needs to be fixed.

1. Navigate to any Nexus mod page's Posts section.
2. Type in a comment.
3. Hit Submit.
4. Error message "There was an error fetching your comment's siblings. Comment not found" will sometimes pop after hitting the Submit button.

Comments posting without an error message.

"There was an error fetching your comment's siblings. Comment not found" error pops up at random times & has become more frequent in recent days.  Please fix this mess.  Beyond ridiculous/annoying.  Thank you.

**Comment by Pickysaurus** [comment] 2020-09-13 20:07
Seems to be a duplicate of #1154 

While I have had it happen maybe once during an extremely heavy load on the site, I'm not able to replicate it, so it may be related to your setup in some way: https://help.nexusmods.com/article/113-troubleshooting-website-issues

Based on your previous reports, it's potentially a bad connection between your PC and our servers.

**Closed by Pickysaurus** 2020-09-13 20:07 UTC
