### ISSUE TITLE
click on category on browse files does nothing

### ISSUE THREAD

**Issue by mouse0270** [Nexus-Mods/web-issues#250] opened 2017-10-28 13:43 UTC
**Bug/error being reported:** click on category on browse files does nothing
**Steps to reproduce:** Go to "Browse all Mods" and click on the category for any of the files
**Expected result:** I would expect it to apply that category as a filter
**Actual result:** Nothing, it just adds a "#" it the URL

**Comment by Thallassa** [comment] 2017-10-28 14:33
I cannot reproduce. When I click on the category, then apply, the category is applied. 

I'm testing on Skyrim. Sometimes errors in search have been game-specific, what game are you testing on?

**Comment by mouse0270** [comment] 2017-10-28 15:18
No, the refine search area works as intended. 

I am saying if you are looking at the "Browse All Mods" page and where the mods are actually. It shows their picture to the left and on the right, it has their name, category, date, author and description. The category under the mods name is a link, but its `href` is set to `#` so it does nothing. I would expect it to auto apply that filter.

**Comment by Fhaarkas** [comment] 2017-10-28 22:47
I think you're talking about 'List' view? Clicking the category just brings you to the top of the page. In 'Tiles' and 'Big Tiles' view clicking category brings you to the appropriate category page as expected.

**Comment by mouse0270** [comment] 2017-10-29 00:10
Maybe, I only ever use list view, I can't stand the look of tiles view

**Comment by verenion** [comment] 2017-10-30 14:42
Assigned PT#152402005

**Comment by verenion** [comment] 2017-10-30 14:49
Fix has been pushed

**Closed by verenion** 2017-10-30 14:49 UTC
Labels: bug
