### ISSUE TITLE
Banner can't be set using existing uploaded images.

### ISSUE THREAD

**Issue by Arindel** [Nexus-Mods/web-issues#144] opened 2017-10-10 01:13 UTC
Missing functionality.

Can't change banner using existing images from modpage.

The only way I can change banner is by uploading another image from PC eventhough it's already uploaded as image on mod page.

**Comment by Rrrafau** [comment] 2017-10-10 09:04
assinged #151835578

**Comment by RoyBatty64** [comment] 2017-10-24 13:05
I reported this back in September and it was closed as can't reproduce.

**Comment by iamtiz** [comment] 2017-11-20 14:47
We added this feature back a few weeks ago

**Closed by iamtiz** 2017-11-20 14:47 UTC
Labels: missing-feature
