### ISSUE TITLE
Search issue - Not displaying most downloaded mod

### ISSUE THREAD

**Issue by Uberbagel** [Nexus-Mods/web-issues#208] opened 2017-10-25 14:56 UTC
When searching for a particular mod with filter set to most downloads, the results are not displaying what should be the most downloaded mod with the name. I have tested this with the skyrim mods Ordinator, Perkus Maximus and Requiem. In all three cases the main mod should presumably be the highest on the list of results, but they aren't even showing up in the results.

**Comment by Thallassa** [comment] 2017-10-25 16:16
What tags do you have blocked and what tags are on these mods? (click "add tag" to view not only tags that have been approved, but also those that have been denied by the mod author).

**Comment by Uberbagel** [comment] 2017-10-25 16:54
The only tags I have blocked are nudity and sexy/skimpy. The tags on the ordinator mod are (Gameplay Effects/Changes, Lore-Friendly, Replacer, Fair and Balanced, English, Scripted Events and Overhaul).

**Comment by Uberbagel** [comment] 2017-10-25 16:58
Okay so I removed those blocked tags and the mods are now showing up in search properly. I'm still pretty sure this is a bug considering none of those mods have those blocked tags.

**Comment by Thallassa** [comment] 2017-10-25 17:32
Related to #185 most likely?

**Comment by Uberbagel** [comment] 2017-10-25 18:30
Seems like it to me. I didn't see that report first or else I would have commented there. Thank you for your help.

**Comment by verenion** [comment] 2017-10-27 09:00
Duplicate of #185

**Closed** 2017-11-16 10:04 UTC
Labels: duplicate
