### ISSUE TITLE
Endorsement bug

### ISSUE THREAD

**Issue by WeirdScience06** [Nexus-Mods/web-issues#1270] opened 2021-01-16 14:24 UTC
## Bug/error being reported:
Endorsement system not functioning correctly

## Steps to reproduce:
None, the site will present the endorsement list at random

## Expected result:
NA

## Actual result:
When endorsing a mod in the list this will be displayed "You have not downloaded this file so you cannot rate it."

**Comment by Pickysaurus** [comment] 2021-01-17 23:01
Duplicate of #1252

**Closed by Pickysaurus** 2021-01-17 23:01 UTC
