### ISSUE TITLE
In mod details text editor scrolls elsewhere when pasting

### ISSUE THREAD

**Issue by avidichard** [Nexus-Mods/web-issues#1158] opened 2020-06-21 13:53 UTC
## Bug/error being reported:
When editing our mod details, almost everytime I copy paste anything, the position of the view inside the editor is changed and I loose where I was. The cursor stays where it is, but for a weird reason, the editor automatically scrolls elsewhere. It's VERY annoying and disturbs a lot when editing long mod details like guides and such.

## Steps to reproduce:
Simply copy something within the editor and paste it elsewhere. This does not happen everytime but to me, it happens almost everytime. let's say, 8 out of 10 times.

## Expected result:
Simply paste whatever we are pasting at the present position without scrolling.

## Actual result:
Scrolls somewhere far up or down automatically but keeps cursor where paste was done.

**Comment by Pickysaurus** [comment] 2020-06-21 15:24
duplicate of #1033

**Closed by Pickysaurus** 2020-06-21 15:24 UTC
