### ISSUE TITLE
Endorsement count has an error

### ISSUE THREAD

**Issue by LamaKreis** [Nexus-Mods/web-issues#1280] opened 2021-01-25 15:54 UTC
## Bug/error being reported:  LamaKreis
Endorsement numbers on the Nexus main pages do not match the endorsement numbers on the mod pages - wrong order in the trending mods

## Steps to reproduce:

1. Open Skyrim Special Edition, 
2. open Mod News, 
3. compare the endorsement numbers of the individual mods on the overall page with the actual number of endorsements on the individual mod pages themselves

## Expected result:
Endorsement number Modpage = 46
Nexus overview page endorsement number = 46

## Actual result:
Endorsement number Modpage = 46
Nexus overview page endorsement number = 18!

**Comment by Pickysaurus** [comment] 2021-01-25 15:56
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1278

We are aware of the delay between the results and the mod page and are working on a fix.

**Closed by Pickysaurus** 2021-01-25 15:56 UTC
