### ISSUE TITLE
cloudflare for both, for web login and forum login not working - NO addons installed!

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1229] opened 2020-10-14 12:55 UTC
it is same for forum login and web login. Have NO addons installed, Cloudflare DDOS protrction not working as usual (i.e. yesterday).

**Comment by BigBizkit** [comment] 2020-10-14 12:56
Hi Dreifels, thanks for the report - it is being looked at right now.

**Comment by WarningHPB** [comment] 2020-10-14 12:58
Having the same issue with no addons enabled in Firefox and Chrome, also tested with Edge with no addons/extentions installed 

Also checked the developer console on Chrome Firefox and Edge and they all show the following:

Chrome:
```
sign_in:1 GET https://users.nexusmods.com/auth/sign_in 503

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

```

Firefox: 
```
GEThttps://users.nexusmods.com/auth/sign_in
[HTTP/2 503 Service Unavailable 23ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 18ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 19ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 23ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 94ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 21ms]

```

Edge: 
```
sign_in:1 GET https://users.nexusmods.com/auth/sign_in 503
v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400
```

Note the error 503

**Comment by WarningHPB** [comment] 2020-10-14 12:59
(side note: I like how the two previous issue was closed with out anyone looking into it assuming it was down to addons, not even asking if addons where enabled)

**Comment by Pickysaurus** [comment] 2020-10-14 13:00
Duplicate of #1227 - please reply to an existing issue rather than opening a new one.

**Closed by Pickysaurus** 2020-10-14 13:00 UTC
