### ISSUE TITLE
Nexus Uploader not working

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1057] opened 2019-11-28 05:59 UTC
## Bug/error being reported:
Uploads on the Nexus are getting stuck/will not work

## Steps to reproduce:
1. Try to upload any file to the Nexus (Skyrim SE Nexus in my case)
2. Watch as the upload fails to progress in any way/shape/form...

## Expected result:
File uploaded to the Nexus

## Actual result:
File failing/refusing to upload...

Seriously, uploading files to the Nexus has been nothing short of a total DISASTER...  This has been an issue for a number of YEARS & yet nothing is being done to correct it...  I know for a fact the Nexus uploader has had issues since I can upload files without issue onto sites like Dropbox &/or MediaFire...  Please get to the bottom of the issues & actually fix the broken mess that is the Nexus uploader...  I should not have to constantly hit the Refresh button on my browser (Mozilla Firefox) just to get a file to upload to the Nexus.  As of right now, uploads are getting stuck & are refusing to work at all period...

**Comment by Pickysaurus** [comment] 2019-12-03 10:01
Duplicate of #1042

**Closed by Pickysaurus** 2019-12-03 10:01 UTC
