### ISSUE TITLE
File hidden, but not displayed as hidden immediately

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#467] opened 2017-12-28 21:52 UTC
File hidden on rd site has not been displayed as that for more than a minute after hiding it (no loading animation or anything like that). Old site: New status has been displayed immediately.
Happened here:
https://rd.nexusmods.com/skyrim/mods/29192
https://old.nexusmods.com/skyrim/mods/29192/?

**Comment by iamtiz** [comment] 2018-01-03 10:00
Duplicate of #459

**Comment by iamtiz** [comment] 2018-01-03 14:13
fixed

**Closed by iamtiz** 2018-01-03 14:13 UTC
Labels: duplicate
