### ISSUE TITLE
"Use Emoticons" Option Only Works on Initial Post, Not Changeable On Edits

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#349] opened 2017-11-12 04:05 UTC
Bug/error being reported: "Use Emoticons" Option Only Works on Initial Post, Not Changeable On Edits
Steps to reproduce: (1) Post a reply with the 'Use Emoticons' box NOT checked (2) Click the 'Edit' linky (3) Make any change and add a deliberate (as opposed to unwanted) Emoticon such as :woot: or :D (4) Check the 'Use Emoticons' checkbox and hit 'Submit' (5) Refresh your page since Nexus does not refresh it automatically after an edit 😞 (6) Refresh the page several more times trying to get your entered Emoticon to parse into the actual symbol instead of the textual equivalent (7) Cry 😢 (8++) Now, make a new post containing the string "Skyrim\Data" with the "Use Emoticons" box checked, refresh the page to force Nexus to update your post whether it wants to or not, and note how the system has changed the "\D" to an unwanted Emoticon, so edit the post and uncheck 'Use Emoticons,' refresh your page and then note that the system has ignored your new choice and is still changing "\Data" to an emote. 😠 
Expected result: Users can add emoticons in subsequent edits after the inital post has been submitted and checking the 'Use Emoticons' will result in the textual code for the Emoticon being changed to the actual graphic Emoticon ==AND== users can DISABLE 'Use Emoticons' in subsequent edits when Nexus spontaneously  changes their entered text into unwanted Emoticons and that new choice will stop Nexus from changing ANY text into an Emoticon.
Actual result: I just don't know why this field is here- I have now described the issue 3 times including once in excruciating detail. Please forgive my ignorance.

**Comment by verenion** [comment] 2017-11-13 11:02
Duplicate of #338

**Closed** 2017-11-15 17:25 UTC
Labels: duplicate
