### ISSUE TITLE
Unexpected results when switching from the old site

### ISSUE THREAD

**Issue by mlandstreet** [Nexus-Mods/web-issues#226] opened 2017-10-26 15:40 UTC
I expected to be switched to the equivalent page in the new site. I would, at least, think I would go to the same game. On the mobile site getting to individual games from the Nexus home page is non-intuitive.

**Comment by mrmason** [comment] 2017-10-26 15:43
Hey - This is a duplicate of #222 - we know it's not perfect, but the alternative is worse. 

Can you let us know what you mean buy getting to the game pages is unintuitive ?

**Closed by mrmason** 2017-10-26 15:43 UTC

**Comment by mlandstreet** [comment] 2017-10-27 05:08
I went to the new site on my Galaxy Note 10,.1 (2012) table where, lo and behold, the links to the games appeared on the main page. 

These do not appear on the Galaxy Note 4 using Samsung Internet or Firefox I have to find the 471 games link to even get to my favorites.
