### ISSUE TITLE
can't see the exact number of downloads when number of downloads exceeds 1.000

### ISSUE THREAD

**Issue by Hilli1** [Nexus-Mods/web-issues#248] opened 2017-10-28 09:01 UTC
Can't see the exact number of downloads on my mod page when the number exceeds 1,000 downloads.

Example: https://rd.nexusmods.com/skyrimspecialedition/mods/11559?

old page: 2,872 Unique D/Ls and 5,671 Total D/Ls 

new page: Unique DLs 2.9k and Total DLs 5.7k

**Comment by mrmason** [comment] 2017-10-28 10:17
Duplicate of #199

**Closed by mrmason** 2017-10-28 10:17 UTC
