### ISSUE TITLE
Unable to edit own posts on owned mod page bug reports 

### ISSUE THREAD

**Issue by skk50** [Nexus-Mods/web-issues#1232] opened 2020-10-16 12:56 UTC
## Bug/error being reported:
Unable to edit own posts on owned mod page bug reports 

## Steps to reproduce:
Login to nexusmods.com as SKK50
Goto page https://www.nexusmods.com/fallout4/mods/34693?tab=bugs
Open bug "Settlers In Power Armor Not Performing Jobs"
Select [Edit Post] on any SKK50 post
Change text (say, to fix spelling)
Press [Submit]

Get ORANGE banner with (!) and no text - post does not update text editor remains on screen.

Happens on all of my bug posts 10 of my tested mods, not just this illustration one. 

## Expected result:
For the editor to close and the post text to update.

## Actual result:
Get ORANGE banner with (!) and no text - post does not update text editor remains on screen.

**Comment by Pickysaurus** [comment] 2020-10-16 12:56
Duplicate of #1219

We're working on it :)

**Closed by Pickysaurus** 2020-10-16 12:56 UTC
