### ISSUE TITLE
Ability to filter mod searches by "downloaded" or "tracking"

### ISSUE THREAD

**Issue by clayne** [Nexus-Mods/web-issues#940] opened 2019-04-29 18:19 UTC
Basically, adding `[ ]` form checkboxes for "downloaded" and "tracking" would *really* help people filter out mods that they're already downloading or tracking.

Related: https://github.com/Nexus-Mods/web-issues/issues/928

**Comment by Pickysaurus** [comment] 2019-04-30 11:53
Duplicate of #928

**Closed by Pickysaurus** 2019-04-30 11:53 UTC

**Comment by clayne** [comment] 2019-04-30 16:55
Not a dupe actually. This is about searched mods not tracked mods (aka tracking centre).  When one searches mods by category, this week’s mods, etc they’re in a totally different mode (use-wise) than what they’re doing in the tracking centre. I realize that on the backend there’s similar things going on but felt it should be a different issue so it doesn’t end up conflated with the tracking centre only. But yes, in general, the issues are the same. The inability to filter out tracked, downloaded, or downloaded+updated mods from both views.

**Comment by Pickysaurus** [comment] 2019-05-01 15:22
I've referenced this issue in the other one as they're related.
