### ISSUE TITLE
Not receiving notifications for tracked files.

### ISSUE THREAD

**Issue by RavenMind** [Nexus-Mods/web-issues#426] opened 2017-12-10 06:24 UTC
## Bug/error being reported:
Notifications for files being tracked are not consistently being shown on the "Updates" tab. Some of the files being tracked are shown, while others are not. Untracking then tracking again seemed to solve the issue for about 1 day, then I was back to not receiving notifications. Verified that the mod is being tracked both in the Tracking Centre, and at the mod page itself. Updates are being displayed under the "Tracked Content Updates" tab in the "More Mods" section, (this is the only way I knew I had updates/notifications).

## Steps to reproduce:
N/A - Have to track a number of mods, then cross-reference them between the "Updates" tab & "Tracked Content Updates" tab.

### Example:

- [Oblivion] [Bevilex's Mod List](https://www.nexusmods.com/oblivion/mods/47591)
- [Oblivion] [Unique Landscapes](https://www.nexusmods.com/oblivion/mods/19370)
- [Oblivion] [Wrye Bash](https://www.nexusmods.com/oblivion/mods/22368) (randomly started working again)
- [Oblivion] [Detailed Terrain](https://www.nexusmods.com/oblivion/mods/15245)
- [Oblivion] [Ruined Tails Tale](https://www.nexusmods.com/oblivion/mods/3027)
- A host of others in my 1,000+ mod tracking list, including Skyrim, SSE, FO4, Morrowind, etc.

## Expected result:
Tracked mods would show up in the Updates tab.

## Actual result:
Tracked mods failed to show up in the Updates tab. Leading to people wondering why I was ignoring their queries.

Even the author of one of the mods (Bevilex), stated he wasn't receiving notifications about his own mod.

Screenshots Attached. (I'd have put them in a spoiler, but I can't seem to find a way to do that here, sorry for the length taken up by them.)
![notifications_not_appearing](https://user-images.githubusercontent.com/30495135/33802617-2299917c-dd38-11e7-85f1-7295468c52fb.jpg)
![notification_preferences](https://user-images.githubusercontent.com/30495135/33802602-001b3a9c-dd38-11e7-8576-e5b86a1dc014.jpg)
![bevilex_tracked_1](https://user-images.githubusercontent.com/30495135/33802608-0b3593aa-dd38-11e7-9202-dcc959b51851.jpg)
![bevilex_tracked_2](https://user-images.githubusercontent.com/30495135/33802609-0e0ade50-dd38-11e7-9508-52166320d3b3.jpg)
![bevilexs_comment](https://user-images.githubusercontent.com/30495135/33802610-11405460-dd38-11e7-8cfc-8761ca868497.jpg)

**Comment by RoyBatty64** [comment] 2017-12-24 12:56
Confirmed, Also not receiving notifications on some tracked files.

For EX https://www.nexusmods.com/newvegas/mods/51664/
I have not received a notification since December 07 and there are quite many posts.

**Comment by iamtiz** [comment] 2018-01-11 15:13
assigned #154249035

**Comment by iamtiz** [comment] 2018-01-12 13:47
This should be fixed now

**Closed** 2018-01-26 11:15 UTC
Labels: bug
