### ISSUE TITLE
parser bug on webpage

### ISSUE THREAD

**Issue by MeitziQ** [Nexus-Mods/web-issues#1594] opened 2022-10-06 15:41 UTC
## Bug/error being reported:
parser bug

## Steps to reproduce:
put text "IncreaseCarLimitOnScene = true" on your mod page  (or on comments etc) 
or "AtGarageLoadAdditionalCarsfromParking ="

## Expected result:
wepage display that text unmodified

## Actual result:
"IncreaseCarLimitjavascript-event-stripped true"   (notice added 'javascript-event-stripped')

This is similar bug to this: 
https://github.com/Nexus-Mods/web-issues/issues/1588

I have not exact timelime on this.

**Comment by Pickysaurus** [comment] 2022-10-13 08:34
Duplicate of #1591

**Closed by Pickysaurus** 2022-10-13 08:34 UTC
