### ISSUE TITLE
Notifications Have Been Erroneously Re-labeled as "Updates"

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#615] opened 2018-03-19 16:29 UTC
## Bug/error being reported:
Within the context of a software-hosting website such as the Nexus, an "Update" is when a mod author releases a new version of her existing mod. In contrast, a notice of activity in a tracked (followed) mod forum page is a "Notification."

For some reason, the new Nexus mod page system has gratuitously relabeled Notifications as "Updates." This is not only semantically incorrect but it is also misleading and confusing as well as counter to industry norms and longstanding past practice at the Nexus.

Please restore the correct and explicit "Notifications" nomenclature to the mislabeled "Updates" links on every Nexus mod page,

**Comment by iamtiz** [comment] 2018-03-20 11:48
Duplicate of #86

**Closed by iamtiz** 2018-03-20 11:48 UTC
Labels: duplicate
