### ISSUE TITLE
Updated mod does not show up on “Last Updated”

### ISSUE THREAD

**Issue by Kungfubellydancer** [Nexus-Mods/web-issues#1622] opened 2022-11-29 03:26 UTC
Kungdubellydancer 

[Jade Springs Goth Mod](https://www.nexusmods.com/morrowind/mods/49900) 

Did not show up on “Last Updated” mod section.

1. I uplooaded a file over 1 GB
2. Saved 11/28
3. Went to “Last Updated” showed over mods but not mine
4. Searched by file name, found Jade Springs Mod but it shows last updated as July, even though it had an “Updated” tag over it.
5. Went back to mod page, it shows Last Updated as 11/28/2022

Please help me fix it as updated it to recently updated list is one of my mod’s few means of exposure, thank you

**Comment by Happybara24** [comment] 2022-12-01 09:23
This problem has been reproduced and will be addressed. Thanks!

**Comment by Pickysaurus** [comment] 2022-12-01 10:44
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1620

**Closed by Pickysaurus** 2022-12-01 10:44 UTC
