### ISSUE TITLE
Cannot remove games (12 game limit)

### ISSUE THREAD

**Issue by drdior** [Nexus-Mods/web-issues#1466] opened 2022-01-28 19:50 UTC
## Your username/username(s) affected
DrDior (self)

## Bug/error being reported:
Nexus Mods will not remove a game in the current selection list (broken).   Can't add games beyond the 12 game limit (not broken)

## Expected result:
game is removed

## Actual result:
nothing removed

**Comment by Pickysaurus** [comment] 2022-01-28 20:47
https://github.com/Nexus-Mods/web-issues/issues/1443

Duplicate of this

**Closed by Pickysaurus** 2022-01-28 20:47 UTC
