### ISSUE TITLE
Mod page not fully loading

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#501] opened 2018-01-12 18:22 UTC
A few people noticed this over the last few days but I saw it for the first time today. 

As a mod page is loading it loads all the images, then the rest of the page.  By the time it fully loads it looks right. 

However this mod page stopped loading before all the content was loaded. It's just stuck with all the images showing in one column, and the rest of the page content below that. It seems to be an issue with the scripts for the gallery not loading or something. Hard refresh/cache clearing didn't help the first few times, eventually the full page loaded and the gallery appeared correct. 

![image](https://user-images.githubusercontent.com/11600099/34889219-35f3ea60-f79b-11e7-8e12-6cf0c6e2da31.png)

https://www.nexusmods.com/skyrimspecialedition/mods/10484/?

**Comment by mrmason** [comment] 2018-01-12 18:28
The problem is the BBoC JS file which contains all of our JS. If that doesn't load then the page isn't going to look right. If it happens again can you check in the network tab and see why it failed to load ?

**Comment by Eolhin** [comment] 2018-01-13 07:07
Okay, I think I found it...  But there is a lot of information on that tab.  There is one red line:
BBoC-1515788812.js
That line repeats a lot of times, before it goes red.  If I click on the red line, I get:
"Failed to load response data"
and the timing tab has a big grey bar for Stalled.
I took a couple of screen shots.  If you need more, or something else there, just say so, and be specific.
![nexus script failure 01](https://user-images.githubusercontent.com/33217711/34903755-3fd1c474-f7ed-11e7-99d1-79ccafb4354e.JPG)
![nexus script failure 02](https://user-images.githubusercontent.com/33217711/34903756-3fe52460-f7ed-11e7-89ef-1ef64452aedb.JPG)

The pages are fairly useless in this state.

**Comment by Eolhin** [comment] 2018-01-13 12:04
Now it is even more completely broken.  Just giant arrows and marks in a vertical column with a few thumbnails.  Same red line and error, when I checked.  Using Chrome.
![nexus script failure 03](https://user-images.githubusercontent.com/33217711/34905880-d5a0198c-f816-11e7-9b7e-d8cfe9a7d3c3.JPG)

**Comment by mrmason** [comment] 2018-01-13 12:08
Now you're not getting the CSS.

What happens if you visit these links directly ?

https://www.nexusmods.com/contents/Scripts/BBoC-1515834987.js
https://www.nexusmods.com/contents/Styles/BBoC-general-1515834987.css

**Comment by Eolhin** [comment] 2018-01-13 12:14
Ghagh!  Entire pages of characters all mashed together, for both of those links.
![nexus script failure 04](https://user-images.githubusercontent.com/33217711/34905955-240c96b2-f818-11e7-9c99-668cf2220c0f.JPG)

Oh, and I just checked, and going back to the old format pages works just fine, if that helps any.

**Comment by mrmason** [comment] 2018-01-13 12:17
That's exactly what you should see - so those resources do work for you if they load them individually. After you've loaded them up - if you then visit the website again - does it work ?

Also, does it work on https://rd.nexusmods.com ?

**Comment by Eolhin** [comment] 2018-01-13 12:22
www.nexusmods.com  now works properly!  No doubt because of force-loading the .js and .css
old.nexusmods.com   works
rd.nexusmods.com     works

But then, I had already opened those thinks you gave me to the scripts, so that might have made a difference in the rd one.

**Comment by Eolhin** [comment] 2018-01-16 08:59
I was hopeful, but it is doing it again.  Just the missing js this time, not the css.
I will try manually loading the scripts from the links you gave me last time, but obviously, something is still broken.

When I try to load the link for the js script, I get:

This page isn’t working
www.nexusmods.com redirected you too many times.
ERR_TOO_MANY_REDIRECTS

The page for the css script (which I don't need right now) still loads fine.

It is possible that (this being an intermittent problem) last time it wasn't loading the js and css pages that solved the problem, but rather the problem resolving itself for a while allowed the pages to load.

Tell me if there is anything I can do to help gather information on this issue.

**Comment by Eolhin** [comment] 2018-01-16 09:07
After several retries, I did get the .js page to load eventually, and forced a refresh of the Nexus page, but loading the .js page evidently did not help at all, as the problem still persists.  I am fairly sure now that the reason everything suddenly started working last time was not because of loading those pages, but rather because the problem had decided to go away again for a while.

**Comment by Eolhin** [comment] 2018-01-16 09:38
...And now it has stopped again, and all three versions are loading correctly (if a bit slow).  I HATE intermittent problems.  *sighs*

**Comment by mrmason** [comment] 2018-01-17 12:06
We've made some changes this morning that should hopefully fix this - can you let us know if you're still experiencing problems ?

**Comment by R0NlN** [comment] 2018-01-17 12:16
At this time, it's working for me.

**Comment by Eolhin** [comment] 2018-01-17 12:24
It is working for me at the moment, but that isn't much of a test, given the problem is intermittent.  If the problem does not come back for four days, or more, I would then say you may have solved it.  (wry smile)  I will post back here if it returns for me.

**Comment by mrmason** [comment] 2018-01-17 13:44
Thanks - I'm hopeful it won't come back, as I think I know what was causing it - I'm going to close this now, but please do let us know if you see anything strange.

**Closed by mrmason** 2018-01-17 13:44 UTC
