### ISSUE TITLE
All notifications getting cleared for all games

### ISSUE THREAD

**Issue by Starfis** [Nexus-Mods/web-issues#359] opened 2017-11-15 18:43 UTC
Bug/error being reported, Steps to reproduce: This is probably more of an enhancement request than a bug report because I don't know how it worked before but... With the start of new site design I started using the "Game-specific notifications" function of updates to make things easier to follow, but when I pressed "clear all notifications" button on the Fallout 4 site, it cleared all notifications across all games not just the ones for Fallout 4. I would expect clearing only notifications for the game on which site I currently am while keeping the other games untouched, I don't play all games I mod at the same time, and newer games have a LOT of notifications so clearing all at once after I open them is definitely handy, but I don't wish to lose updates for older games. Sorry for a novel format.

**Comment by iamtiz** [comment] 2017-11-16 10:40
Duplicate of #303

**Comment by iamtiz** [comment] 2017-11-17 12:10
Fixed

**Closed by iamtiz** 2017-11-17 12:10 UTC
Labels: duplicate
