### ISSUE TITLE
Current issues with different browsers

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#395] opened 2017-11-28 12:33 UTC
Nexus user name: zcul
Issue with Chrome:
1. Sometimes only upper half of a mod page is displayed.
2. Currently I cannot change from a user’s forum profile to the Nexus profile (blank page on old site design).

Issue with Firefox:
I cannot log in on the new rd-site („wrong password“), while log in on the old site design works fine.

**Comment by Elynda** [comment] 2017-11-28 23:10
Nexus user name: Elynda
Issue with Microsoft Edge:

Options are not populating in dropdown boxes, such as Category when trying to submit an image.  Works fine in Internet Explorer.

**Comment by zcul** [comment] 2017-11-28 23:20
1. Same issues occur with Edge (only half of the page displayed when selecting the link in a report)
2. Attached 3 screenies concerning the issues and issue especially with Chrome.
Apart from that, thank you guys for your work and commitment ...
![01 half display on rd site](https://user-images.githubusercontent.com/31516762/33349584-12d71d7c-d49b-11e7-832d-de0fc16abb03.jpg)
![02 open nexus profile](https://user-images.githubusercontent.com/31516762/33349585-12f0c8ee-d49b-11e7-84c5-b0258a4d5519.jpg)
![03 chrome linking to rd site](https://user-images.githubusercontent.com/31516762/33349587-1309a3be-d49b-11e7-8ea1-9104ceec74b8.jpg)

**Comment by iamtiz** [comment] 2017-12-12 15:15
Forum profile issue confirmed and assigned to #153597432.

Are the other issues still happening?

**Comment by Elynda** [comment] 2017-12-13 00:43
drop-down boxes still not populating

**Comment by iamtiz** [comment] 2017-12-13 09:10
@Elynda does the 'You must select a game first' message appear, or nothing at all?

**Comment by iamtiz** [comment] 2017-12-18 13:41
The forum profile issue has been fixed.

Still unable to replicate the drop-down problem

**Comment by Elynda** [comment] 2017-12-30 17:39
Issue seems to be with my laptop.  Works fine in Edge on pc.

**Closed** 2018-02-28 09:11 UTC
Labels: cant-replicate
