### ISSUE TITLE
updating date of downloads on description page, Witcher 3

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#19] opened 2017-09-05 21:22 UTC
https://rd.nexusmods.com/witcher3/mods/2608?tab=description
This page (Witcher 3) says, that I **last** downloaded a file from this mod on **16** Aug 2017.
Actually I **first** downloaded a file from this mod on **16** Aug 2017.
I **last** downloaded a file from this mod on **26** Aug 2017.
Nothing essential for me personally, but might be confusing ...
Thank you guys for the great job you do ;-)

![download update on description page](https://user-images.githubusercontent.com/31516762/30083966-ccd8de6a-9290-11e7-8998-c31300791c8b.jpg)

**Comment by verenion** [comment] 2017-09-12 13:09
Assigned PT#151006353

**Comment by verenion** [comment] 2017-09-12 14:08
This is caused by another known issue PT#150170352. Will update here when that task is complete.

**Comment by verenion** [comment] 2017-09-12 15:41
Fix has been pushed.

**Closed by verenion** 2017-09-12 15:41 UTC
Labels: bug
