### ISSUE TITLE
Top Banner says there are updates, but there are none

### ISSUE THREAD

**Issue by professionaljones** [Nexus-Mods/web-issues#113] opened 2017-10-02 17:59 UTC
Title says it all. Not sure if bug or just affects me personally.

<img width="1920" alt="screen shot 2017-10-02 at 1 59 12 pm" src="https://user-images.githubusercontent.com/3934211/31091722-e7b935ba-a779-11e7-9ec1-d503ba4d5a4b.png">

**Comment by verenion** [comment] 2017-10-03 08:52
Assigned PT#151632561

**Comment by Thallassa** [comment] 2017-10-04 16:01
I can confirm. This just happened to me this morning; yesterday I received no updates at all. 

Steps to replicate:

Logged onto nexus. Had 4 updates. Only 3 were new (not greyed out). Clicked on those three. It still said I had one update, even though all visible updates were greyed out.

**Comment by iamtiz** [comment] 2017-10-04 16:01
This should now be fixed

**Comment by mrmason** [comment] 2017-10-05 18:00
Looks like this is still occurring for some users - reported in #137 by @heavyoak

**Comment by iamtiz** [comment] 2017-10-06 12:47
Is anyone still experiencing this issue?

**Comment by Thallassa** [comment] 2017-10-06 14:58
It is no longer happening for me.

**Comment by professionaljones** [comment] 2017-10-06 15:49
Nope, not seeing it.

**Comment by heavyoak** [comment] 2017-10-07 01:27
its fixed for me as well.

**Comment by mrmason** [comment] 2017-10-10 10:44
Thanks guys - closing.

**Closed by mrmason** 2017-10-10 10:44 UTC
Labels: bug
