### ISSUE TITLE
Reordering mod page images in the media section doesn't work properly

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#332] opened 2017-11-07 23:15 UTC
When reordering images of a mod page in the media section (```/mods/edit/?id=<id>&game_id=<id>&step=media```), things don't appear in the spot where you put them in after refreshing the page at all.

This is not a caching issue. Sometimes, there is no change at all and sometimes images get shuffled from and into random locations. Don't know if relevant, but the mod pages in question were all duplicated from Oldrim to SSE. I haven't had a chance to test it on newly created mod pages yet, unfortunately.

I noticed that usually, dragging the LEFT image over to the image to the RIGHT beside it works and saves correctly. However, moving images from/to random places doesn't.

Expected result: After refreshing the page, you should have the images ordered how they were before refreshing.

Steps to reproduce: Duplicate/make a mod page, upload images (or keep the existing ones from duplication) and attempt to reorder them in the media section.

Feel free to ask for more details if it can be reproduced or something is weird.

**Comment by ousnius** [comment] 2017-11-07 23:37
Duplicate of #325, sorry. I didn't realize with thumbnails he meant images in general.

**Comment by verenion** [comment] 2017-11-08 10:26
Duplicate of #325

**Closed by verenion** 2017-11-08 10:26 UTC
