### ISSUE TITLE
Not displayed the contents of the archive.

### ISSUE THREAD

**Issue by AKSYON0V** [Nexus-Mods/web-issues#519] opened 2018-01-19 08:26 UTC
## Bug/error being reported:
After you download fashion RAR files, and the nation knock preview file content - message appears: error when you open the 7zip files. I would like to know is it a real error? And how to get rid of this label? Restart the archive helps, the error sometimes disappears, but I don't understand why this happens even if I load the mod files in the rar initially. In addition, the description says the zip is not forbidden - but if I understand correctly, it turns out that in a zip archive to view the contents not?

## Steps to reproduce:
Packed in a rar archive on your computer the files esp + bsa + bsa, 50% to 50%, a message appears after downloading and trying to view the contents of files.

## Expected result:
I just want to know the reason for this message.

## Actual result:
I want to view the contents of any of my archives on the site!
![x1](https://user-images.githubusercontent.com/35535377/35141278-f4380ef2-fd13-11e7-8026-f4d7065db7b3.jpg)

**Comment by iamtiz** [comment] 2018-01-19 12:20
Duplicate of #449

**Comment by iamtiz** [comment] 2018-01-25 14:27
The problem with the archive preview pop-up is now fixed (https://www.nexusmods.com/skyrimspecialedition/mods/14713)

**Closed by iamtiz** 2018-01-25 14:27 UTC
Labels: duplicate
