### ISSUE TITLE
Report an ad bug

### ISSUE THREAD

**Issue by Arrow2thekn33** [Nexus-Mods/web-issues#298] opened 2017-11-01 01:17 UTC
Bug/error being reported:  The item you are trying to report could not be found
Steps to reproduce: Click on "report an ad" on any ad
Expected result: page to report ad
Actual result: Error "The item you are trying to report could not be found"

**Comment by Rrrafau** [comment] 2017-11-01 11:05
assigned #152469988

**Comment by mrmason** [comment] 2017-11-01 12:45
This was also a duplicate of `PT#152274710`

**Closed by mrmason** 2017-11-01 12:45 UTC
Labels: bug
