### ISSUE TITLE
Nexus 5: keeps opening add instead of what I'm selecting

### ISSUE THREAD

**Issue by Marie-EveBenoit** [Nexus-Mods/web-issues#207] opened 2017-10-25 14:55 UTC
On my nexus 5, Android 6.0.1, chrome browser.

When I try to select an item of a list (Ex: Trending mods list in the Skyrim mods sections), the whole page seems to be selected and open an add in an other tab. Selecting the picture to open in an other tab doesn't work.

If I want to consult a mod, I need to precisely select the + icon and choose view mod page. The + being kinda small on my phone, it's not great. I kinda open multiple adds before being able to select the +.

**Comment by davethegamer** [comment] 2017-10-25 16:32
Dark (Official Nexus Discord Moderator): Yeah, that's a very fooking annoying issue our ad provider has introduced, Hopefully they'll sort it when they wake up.

They’ll fix it soon, this issue has also been reported before.

**Comment by verenion** [comment] 2017-10-27 08:59
Duplicate of #203

**Comment by verenion** [comment] 2017-10-27 09:00
This should be resolved now.

**Closed by verenion** 2017-10-27 09:00 UTC
Labels: duplicate
