### ISSUE TITLE
Banner link redirects to http://www.cokeworlds2017.com/?campaign=Curse

### ISSUE THREAD

**Issue by kcbennett1** [Nexus-Mods/web-issues#204] opened 2017-10-25 11:59 UTC
I am not sure if this is a bug or a prank and intentional, but I can assure you it is annoying as hell.

**Comment by rscottexe** [comment] 2017-10-25 12:01
Hello, it's a bug with the ad code we're being given from our provider.

Please can you let me know what country you're in so I can test this? I'm in the UK and I don't see this ad, so I can't test it. If I know the country, I can use a VPN to take a look.

Thanks and sorry for the hassle.

**Comment by kcbennett1** [comment] 2017-10-25 12:04
I am in the Ulcered Sphincter of Alcerica the USA

**Comment by rscottexe** [comment] 2017-10-25 12:05
Sorry, could you also give the State as well, please? I'm using a US VPN but can't reproduce it, so it might even be targetted to a specific state.

**Comment by kcbennett1** [comment] 2017-10-25 12:05
Georgia, or as I prefer to think of it as hell on earth

**Comment by rscottexe** [comment] 2017-10-25 12:05
Haha, thank you.

**Comment by kcbennett1** [comment] 2017-10-25 12:07
sometimes I can get through on my cell phone, or tablet and even occasionally on the computer but always at some point I get this coca cola splash page. I don't even drink soda.

**Comment by rscottexe** [comment] 2017-10-25 12:08
I can appreciate it's pissing annoying. It's pissing annoying for us too considering how much commission ad providers take -- I expect them to be able to provide a service without mucking up our site.

Thanks for your patience, we'll get it sorted ASAP.

**Comment by kcbennett1** [comment] 2017-10-25 12:08
From what I can see the new layout is going to be great for mobile platforms before I couldn't even get to my download history from my phone and sometimes need to check mod parameters.

**Comment by kcbennett1** [comment] 2017-10-25 12:20
Now it is for Alien (under) Ware PCs

**Comment by rscottexe** [comment] 2017-10-25 12:30
The people who need to fix this are West Coast so they won't even be awake yet -_-

**Comment by verenion** [comment] 2017-10-26 16:13
Duplicate of #203

**Comment by verenion** [comment] 2017-10-26 16:16
This issue should have been sorted.

**Closed by verenion** 2017-10-26 16:16 UTC
Labels: duplicate

**Comment by kcbennett1** [comment] 2017-10-26 17:19
Yup was working really well last night.  Love the new site layout.

"Well done is better than well said."
 ~Benjamin Franklin

Sent with [ProtonMail](https://protonmail.com) Secure Email.
