### ISSUE TITLE
Tag filtering not working

### ISSUE THREAD

**Issue by Ouch660** [Nexus-Mods/web-issues#1213] opened 2020-09-27 15:44 UTC
## Bug/error being reported:
Still seeing Translation mods on Skyrim SE page despite that tag being selected to hide in site preferences, mods with unwanted tags in New this week and search results

**Comment by Pickysaurus** [comment] 2020-09-27 17:15
Duplicate of #1212

**Closed by Pickysaurus** 2020-09-27 17:15 UTC
