### ISSUE TITLE
Tracked Mods no longer listed in Tracking Center

### ISSUE THREAD

**Issue by PhDGaming** [Nexus-Mods/web-issues#1251] opened 2020-12-19 20:11 UTC
## Bug/error being reported:
Since becoming a Premium Member all of the mods I have tagged as "Tracking" are no longer being listed in the Tracking Center. I have found several mods and verified that these mods are in fact still tagged. 

## Steps to reproduce:
When I select the option to display "Tracked Mods" to display the Tracking Center, this page is displayed but no mods are listed. 

## Expected result:
Should display a list of all mods for the selected game that are tagged as "Tracking".

## Actual result:
No mods are displayed even though the tab shows I have 24 tracked mods.

![Mod 1](https://user-images.githubusercontent.com/54459270/102698562-9659db00-41fb-11eb-8ab1-3f7cf4194983.png)

![Mod 2](https://user-images.githubusercontent.com/54459270/102698570-a07bd980-41fb-11eb-8e4d-6003c4f240af.png)

![web page](https://user-images.githubusercontent.com/54459270/102698579-a8d41480-41fb-11eb-96c3-57b527214ede.png)

**Comment by Pickysaurus** [comment] 2020-12-20 17:59
Please ensure you try and replicate this with no browser addons enabled. 9/10 time this kind of problem is caused by overzealous "privacy" addons, adblockers or security settings which block the Javascript required to display the page.

**Comment by HighM4inten4nce** [comment] 2020-12-22 19:28
Got the same problem. Turned off shields.
![image](https://user-images.githubusercontent.com/76494840/102925689-e0dc9100-4461-11eb-92a7-feae6486b42f.png)

**Comment by PhDGaming** [comment] 2020-12-23 20:08
I've removed all addons and still get the same result. I also don't block Javascript so I know that is not the issue either.

**Comment by boyer92** [comment] 2021-01-08 22:33
Found a fix! You can click on the items showing drop down menu and click 60 items.

**Comment by rafaasmiranda** [comment] 2021-01-12 13:28
I have the same issue. Selecting 60 items in the "Show" drop down made list appear again.  
To me it first happened after purchasing a premium subscription.  
username: rafaasmiranda

**Comment by Pickysaurus** [comment] 2021-01-13 08:51
Thanks for the updates @boyer92 and @rafaasmiranda , while we still can't reproduce this that does give us a place to start.

**Comment by rafaasmiranda** [comment] 2021-02-06 15:22
@Pickysaurus I don't know if anything was done, but the tracked mods list is now been shown correctly with the default 20 items listing.

![Screenshot_120](https://user-images.githubusercontent.com/25139026/107122334-eeb16e80-6875-11eb-9f73-00b870ff0142.png)

**Comment by chrisharrison** [comment] 2021-02-06 15:50
A fix for this was released on 28th Jan.

**Closed by chrisharrison** 2021-02-06 15:50 UTC
Labels: cant-replicate
