### ISSUE TITLE
cannot login - DDoS protection by Cloudflare not working correctly

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1227] opened 2020-10-14 12:22 UTC
it says wait 5 sec, but it does not proceed
for more than 1 hr same, after click on login 
Firefox 81.02
![000](https://user-images.githubusercontent.com/40837496/95988069-9f5bb400-0e28-11eb-99ed-a26ea91e6cf1.jpg)

**Comment by Pickysaurus** [comment] 2020-10-14 12:23
https://forums.nexusmods.com/index.php?/topic/9200853-sign-in-with-firefox/#entry86003708
^ Forum post discussing this.

It is caused by browser addons.

**Comment by Dreifels** [comment] 2020-10-14 12:42
no, what addon? for this site all are disabled

**Comment by WarningHPB** [comment] 2020-10-14 12:57
Having the same issue with no addons enabled in Firefox and Chrome, also tested with Edge with no addons/extentions installed 

Also checked the developer console on Chrome Firefox and Edge and they all show the following:

Chrome:
```
sign_in:1 GET https://users.nexusmods.com/auth/sign_in 503

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.7509278249296522:1602662637:b0aa0cb69bc4593658f6a99c735a655777f3ad45b83ab79b927656a57a1111e5/5e216bcf58aee674/90c510b05b47025 400

```

Firefox: 
```
GEThttps://users.nexusmods.com/auth/sign_in
[HTTP/2 503 Service Unavailable 23ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 18ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 19ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 23ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 94ms]

XHRPOSThttps://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.5619440908767261:1602662635:75001b08a38f8b04b584ddb94f2a0c0c169f4d66f7ae720f6ed87b3340ef521b/5e2171c279cd070a/804f14fa1cb8b68
[HTTP/2 400 Bad Request 21ms]

```

Edge: 
```
sign_in:1 GET https://users.nexusmods.com/auth/sign_in 503
v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400

v1:1 POST https://users.nexusmods.com/cdn-cgi/challenge-platform/h/g/generate/ov1/0.04291613673817439:1602662627:ca2f708930728dacc0f951e2abaf5416ded8c898e8a8c2e9f45c8bbf581bb036/5e2174987d20e5fc/9e5a3f45bdbb2d4 400
```

Note the error 503

**Comment by Pickysaurus** [comment] 2020-10-14 13:14
We have made some tweaks to our CloudFlare settings which should resolve this issue where it isn't caused by addons.

**Comment by Pickysaurus** [comment] 2020-10-14 13:22
CloudFlare themselves are currently reporting issues, so this may be related: https://www.cloudflarestatus.com/

**Comment by Dreifels** [comment] 2020-10-14 13:45
Düsseldorf, my connection, is "operable"

**Comment by Xroft666** [comment] 2020-11-02 21:59
just drop cloudflare already, they are as good as ddos itself

**Comment by Pickysaurus** [comment] 2020-11-03 16:52
We've had no further reports, closing this.

**Closed by Pickysaurus** 2020-11-03 16:52 UTC
