### ISSUE TITLE
cnt login, captcha puzle frame not appear

### ISSUE THREAD

**Issue by elpsyho** [Nexus-Mods/web-issues#1173] opened 2020-07-28 12:05 UTC
## Bug/error being reported:
cnt login, captcha puzle frame not appear

## Steps to reproduce:
use opera and mozilla v.56 browser . no adblokers, av turned off.

### Example:
in browser console i can see:
Content Security Policy: Игнорирую «https://assets.hcaptcha.com» внутри script-src: указано «strict-dynamic» (неизвестен)
Content Security Policy: Игнорирую «'unsafe-inline'» внутри script-src: указано «strict-dynamic» (неизвестен)
Content Security Policy: Игнорирую «https:» внутри script-src: указано «strict-dynamic» (неизвестен)
/its mean- ignoring «strict-dynamic»

its look strange- i use mozilla ver 56 and mozilla support CSP3 since 52 version...
can u built in captcha in compatibility mode or something like that?

## Expected result:
solve captcha->log in
## Actual result:

cnt log in

**Comment by Pickysaurus** [comment] 2020-07-28 12:07
Possible duplicate of https://github.com/Nexus-Mods/web-issues/issues/1171

Or it's being caused by your browser settings/add-ons: https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Closed by Pickysaurus** 2020-07-28 12:07 UTC

**Comment by elpsyho** [comment] 2020-07-28 12:14
its not a duplicate. its detailed information. in #1171 no browser console information. and its NOT nexus issue- its captcha included in nexus site issue.
or its quick way to solve issue- just close them? i readed ur link(there no my case), i have no issue in NEXUS site, just problem with damn captcha.

**Comment by elpsyho** [comment] 2020-07-29 01:35
now captcha work correctly and login was ok. btw nothing was changed, even pc/browser dnt restarted.

**Comment by Pickysaurus** [comment] 2020-07-29 11:50
We fixed is #1171 - so it probably was related ;)
