### ISSUE TITLE
Translation mod don't appear II

### ISSUE THREAD

**Issue by Gothuska** [Nexus-Mods/web-issues#1304] opened 2021-02-19 01:42 UTC
This translation mod Unofficial Patch NVSE Plus - Es https://www.nexusmods.com/newvegas/mods/71374/
don't appear in nexus fallout nv page and dont't appear too on my mod page https://www.nexusmods.com/users/42430300?tab=user+files
I have been blocked?

**Comment by Pickysaurus** [comment] 2021-02-19 09:07
Duplicate of #1303

**Closed by Pickysaurus** 2021-02-19 09:07 UTC
