### ISSUE TITLE
Nexus Mod Version often doesn't match the actual mod version or is not a valid version number

### ISSUE THREAD

**Issue by Sorbe** [Nexus-Mods/web-issues#1253] opened 2020-12-22 04:25 UTC
Please help the mod developers get their version numbering correct.  Issues include:

1. Submitting mods without any version number at all, breaking updating.
2. Submitting updated filenames that don't match the contained mods' version
2. Submitting updates that don't match the announced mod version by the nexus site.
3. Submitting updates whose version number is non-standard and confuses mod installers.
4. Submitting FOMOD installer whose internal version number doesn't match the mod version

**Comment by Pickysaurus** [comment] 2021-01-03 12:16
This is not a bug with the site, so I will close this issue.

We are slowly nudging mod authors towards using proper semantic versioning.

**Closed by Pickysaurus** 2021-01-03 12:16 UTC
