### ISSUE TITLE
List of my User files is empty

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1456] opened 2022-01-05 17:29 UTC
https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files&BH=1
219 Userfiles there should be shown (and had shown until some hrs ago)
now it is empty, find no way to get them back.
![000](https://user-images.githubusercontent.com/40837496/148261956-15735c30-2bd5-4d3e-95b0-1e7f74ceb2a8.jpg)

**Comment by MaxAper** [comment] 2022-01-05 18:16
This happens not only in the User Files tab. New Mods, More Trending, Popular and even Search menu are giving empty results.

**Comment by sabatinator** [comment] 2022-01-05 18:22
Having the same issue with both user files and search bar. I can confirm that Skyrim LE Nexus is working fine, though

![nexus_searchbug](https://user-images.githubusercontent.com/50128414/148268693-afa30332-f644-4af2-b9e5-afdcd3128344.png)
.

**Comment by DIBZ42** [comment] 2022-01-05 18:31
I'm also having an issue causing no mods to show for ANY game page.... 
![Screenshot (74)](https://user-images.githubusercontent.com/97190045/148269734-df26f673-36c7-4329-ad82-9dee97df45ae.png)

**Comment by JojoGithub-00** [comment] 2022-01-05 18:51
Same issue here......
![image](https://user-images.githubusercontent.com/70440612/148272412-e4ec9411-9d7a-4b32-91cc-b5e5ff4185f9.png)

**Comment by Dreifels** [comment] 2022-01-05 18:53
and now, after correct wrking for ~ 1 hr, - all sort order is corrupt.

**Comment by Pickysaurus** [comment] 2022-01-05 19:05
Duplicate of #1454

**Closed by Pickysaurus** 2022-01-05 19:05 UTC
